version: 2.1
jobs:
  # running commands on a basic image
  Hello-World:
    docker:
      - image: alpine:3.15
        auth:
          username: Charles_Wei_1991@126.com
          password: $Heri9Zailai
    steps:
      - run:
          name: Saying Hello
          command: |
            bundle exec fastlane ios CI0403
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  # fetching code from the repo
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: Charles_Wei_1991@126.com
          password: $Heri9Zailai
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  # running a node container
  Using-Node:
    docker:
      - image: cimg/node:17.2
        auth:
          username: Charles_Wei_1991@126.com
          password: $Heri9Zailai
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'The work is now complete.'
workflows:
  Example-Workflow:
    jobs:
      - Hello-World:
        filters:
          branches:
            ignore:
              - develop
      # - Fetch-Code:
      #   - Hello-World
      # - Using-Node:
      #     requires:
      #       - Fetch-Code
      # - Now-Complete:
      #     requires:
      #       - Using-None
      #       - Fetch-Code
            
